### ISSUE TITLE
Like sdf_unnest(), but for bare structs

### ISSUE THREAD

**Issue by tdsmith** [mitre/sparklyr.nested#10]
I have a struct-type column where I'd like to promote all of its members one level. Using sdf_unnest I get an error:

> org.apache.spark.sql.AnalysisException: The number of aliases supplied in the AS clause does not match the number of columns output by the UDTF expected 2 aliases but got event_map_values

which I assume arises because it's a bare struct and not an array-of-structs.

Could/should this work on structs?

**Comment by mattpollock** [comment]
Your diagnosis is correct. Right now `sdf_unnest` always calls `sdf_explode` and `sdf_select`. In the bare struct case we only want to call `sdf_select` with some helpers to figure out field names and such. This has been on my list. I'm at the beach next week but will get something after that.

**Comment by mattpollock** [comment]
@tdsmith this turned out to be pretty easy. Can you test out the `feature/unnest` branch and let me know how that goes?

**Comment by mattpollock** [comment]
resolved with #13
