### ISSUE TITLE
sdf_select warning:  “`select_vars()` is deprecated as of dplyr 0.8.4.

### ISSUE THREAD

**Issue by EarlGlynn** [mitre/sparklyr.nested#26]
Do we need an update to get rid of this warning?

I'm using `sdf_select` to  extract fields from a nested structure like this:

```
sampleRecords <-
  xxxThing                %>%
  sdf_select(id1,
             id2,
             thingId      = thingcode.standard.id,
             thingCoding  = thingcode.standard.codingSystemId,
             thingDisplay = thingcode.standard.primaryDisplay,
             date1,
             date2)       %>%
  head(2)                                              
```
All works fine, but there's this warning:

```
Warning message:
“`select_vars()` is deprecated as of dplyr 0.8.4.
Please use `tidyselect::vars_select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.”
```

**Comment by mattpollock** [comment]
This [is fixed](https://github.com/mitre/sparklyr.nested/commit/1c8dadd5aa563738bf7a373a8dbb4cb9dd824b08) in the development version. I'll consider pushing a new version to CRAN in the coming weeks.

**Comment by aonurdemir** [comment]
Now it says:
`select_vars()` was deprecated in dplyr 0.8.4 and is now defunct.
Please use `tidyselect::vars_select()` instead.

**Comment by mattpollock** [comment]
Are you using version `0.0.4`?
