### ISSUE TITLE
spark_write_json or spark_write_parquet don't with with nested fields starting with "_"

### ISSUE THREAD

**Issue by admoseremic** [mitre/sparklyr.nested#29]
Hi, I have a spark data frame that I'm nesting under a key that starts with an underscore "_". Using the schema viewer, you can see it seems to work just fine:

![image](https://user-images.githubusercontent.com/5819096/163659016-2eb3362b-b9b0-43f3-9ba6-92526e1bb1a5.png)

However, when I try to write the data to disk using spark_write_json or spark_write_parquet, it throws a weird error:
Error in `chr_as_locations()`:
! Can't subset columns that don't exist.
x Column `X_amc` doesn't exist.

It's like it's adding an "X" on the front or something. Additionally, if I do just a simple "collect()" to collect the spark data frame direclty into my R environment, it seems to work fine too:

![image](https://user-images.githubusercontent.com/5819096/163659103-740a2f00-f99d-4daf-8648-71ebaa1fb520.png)

Not sure what's going on, but it seems to be some bad interaction between sparklyr.nested and the spark_write functions.

**Comment by mattpollock** [comment]
It isn't clear to me how this issue involves `sparklyr.nested` except that you used `sdf_schema_viewer` successfully. The `spark_write_*` functions come from `sparklyr`. Am I missing something?
