### ISSUE TITLE
support nesting like tidyr::nest

### ISSUE THREAD

**Issue by mattpollock** [mitre/sparklyr.nested#3]
Use case:

Maps can be difficult to work with. The `explode` method will blow them up to a struct with fields `key` and `value`. However what if a user wants a map type be useful without also promoting the data with respect to nestedness? Something like

    df %>%
      sdf_explode(map_field, is_map=TRUE) %>%
      sdf_nest(key, value)

could be wrapped in a single `sdf_unmap` (or `sdf_map_to_struct`) function to convert between data types.

**Comment by davidroberson** [comment]
This is such a great R package for me.  I used sdf_nest and sdf_select with sparklyr.  Very helpful.

**Comment by mattpollock** [comment]
This can be done using [`collect_list`](https://spark.apache.org/docs/2.3.1/api/java/org/apache/spark/sql/functions.html#collect_list-org.apache.spark.sql.Column-)
