### ISSUE TITLE
select_vars()

### ISSUE THREAD

**Issue by domorev** [mitre/sparklyr.nested#30]
`select_vars()` was deprecated in dplyr 0.8.4.
ℹ Please use `tidyselect::vars_select()` instead.
ℹ The deprecated feature was likely used in the sparklyr.nested package.

**Comment by mattpollock** [comment]
This [is fixed](https://github.com/mitre/sparklyr.nested/commit/1c8dadd5aa563738bf7a373a8dbb4cb9dd824b08) in the development version. I'll consider pushing a new version to CRAN in the coming weeks.
