### ISSUE TITLE
provide a (small) nested dataset to try the functions on

### ISSUE THREAD

**Issue by henningsway** [mitre/sparklyr.nested#7]
When I use sparklyr(.nested) on my local machine, I do not have acces to nested data right away. It would be easier to experiment with e.g. `sdf_exploder()` if a small nested dataset would come with the package or could be downloaded somewhere.

Or do you have any other suggestions how to best testdrive this package on nested data?

**Comment by bhogan-mitre** [comment]
Probably the quickest way to get nested test data is to use `sdf_nest` to take some flat data as input and create a nested version of it.  There is an example here that should help get started: https://github.com/mitre/sparklyr.nested/blob/master/R/nest.R#L14-L19

Does that work for you?
